version: '3.8'

services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  frontend:
    build: ./frontend
    ports:
      - "3000:80"

  nginx:
    image: nginx
    ports:
      - "8080:80"
    depends_on:
      - frontend

volumes:
  mongo-data:
