version: '3.8'

services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/amis_solidaires
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    ports:
      - "3000:80"

  nginx:
    image: nginx
    ports:
      - "8080:80"
    depends_on:
      - frontend
      - backend

volumes:
  mongo-data:
